config/routes.rb
Zorgkostenmonitor::Application.routes.draw do
  resources :zorgproductgroeps

  resources :zorgproducts

end

app/models/zorgproduct.rb
class Zorgproduct < ActiveRecord::Base
end

app/models/zorgproductgroep.rb
class Zorgproductgroep < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/zorgproductgroeps_controller.rb
class ZorgproductgroepsController < ApplicationController
  # GET /zorgproductgroeps
  # GET /zorgproductgroeps.json
  def index
    @zorgproductgroeps = Zorgproductgroep.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zorgproductgroeps }
    end
  end

  # GET /zorgproductgroeps/1
  # GET /zorgproductgroeps/1.json
  def show
    @zorgproductgroep = Zorgproductgroep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zorgproductgroep }
    end
  end

  # GET /zorgproductgroeps/new
  # GET /zorgproductgroeps/new.json
  def new
    @zorgproductgroep = Zorgproductgroep.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zorgproductgroep }
    end
  end

  # GET /zorgproductgroeps/1/edit
  def edit
    @zorgproductgroep = Zorgproductgroep.find(params[:id])
  end

  # POST /zorgproductgroeps
  # POST /zorgproductgroeps.json
  def create
    @zorgproductgroep = Zorgproductgroep.new(params[:zorgproductgroep])

    respond_to do |format|
      if @zorgproductgroep.save
        format.html { redirect_to @zorgproductgroep, notice: 'Zorgproductgroep was successfully created.' }
        format.json { render json: @zorgproductgroep, status: :created, location: @zorgproductgroep }
      else
        format.html { render action: "new" }
        format.json { render json: @zorgproductgroep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zorgproductgroeps/1
  # PUT /zorgproductgroeps/1.json
  def update
    @zorgproductgroep = Zorgproductgroep.find(params[:id])

    respond_to do |format|
      if @zorgproductgroep.update_attributes(params[:zorgproductgroep])
        format.html { redirect_to @zorgproductgroep, notice: 'Zorgproductgroep was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @zorgproductgroep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zorgproductgroeps/1
  # DELETE /zorgproductgroeps/1.json
  def destroy
    @zorgproductgroep = Zorgproductgroep.find(params[:id])
    @zorgproductgroep.destroy

    respond_to do |format|
      format.html { redirect_to zorgproductgroeps_url }
      format.json { head :ok }
    end
  end
end

app/controllers/zorgproducts_controller.rb
class ZorgproductsController < ApplicationController
  # GET /zorgproducts
  # GET /zorgproducts.json
  def index
    @zorgproducts = Zorgproduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zorgproducts }
    end
  end

  # GET /zorgproducts/1
  # GET /zorgproducts/1.json
  def show
    @zorgproduct = Zorgproduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zorgproduct }
    end
  end

  # GET /zorgproducts/new
  # GET /zorgproducts/new.json
  def new
    @zorgproduct = Zorgproduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zorgproduct }
    end
  end

  # GET /zorgproducts/1/edit
  def edit
    @zorgproduct = Zorgproduct.find(params[:id])
  end

  # POST /zorgproducts
  # POST /zorgproducts.json
  def create
    @zorgproduct = Zorgproduct.new(params[:zorgproduct])

    respond_to do |format|
      if @zorgproduct.save
        format.html { redirect_to @zorgproduct, notice: 'Zorgproduct was successfully created.' }
        format.json { render json: @zorgproduct, status: :created, location: @zorgproduct }
      else
        format.html { render action: "new" }
        format.json { render json: @zorgproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zorgproducts/1
  # PUT /zorgproducts/1.json
  def update
    @zorgproduct = Zorgproduct.find(params[:id])

    respond_to do |format|
      if @zorgproduct.update_attributes(params[:zorgproduct])
        format.html { redirect_to @zorgproduct, notice: 'Zorgproduct was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @zorgproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zorgproducts/1
  # DELETE /zorgproducts/1.json
  def destroy
    @zorgproduct = Zorgproduct.find(params[:id])
    @zorgproduct.destroy

    respond_to do |format|
      format.html { redirect_to zorgproducts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zorgproductgroeps_helper.rb
module ZorgproductgroepsHelper
end

app/helpers/zorgproducts_helper.rb
module ZorgproductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zorgkostenmonitor</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zorgproductgroeps/_form.html.erb
<%= form_for(@zorgproductgroep) do |f| %>
  <% if @zorgproductgroep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zorgproductgroep.errors.count, "error") %> prohibited this zorgproductgroep from being saved:</h2>

      <ul>
      <% @zorgproductgroep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :omschrijving %><br />
    <%= f.text_area :omschrijving %>
  </div>
  <div class="field">
    <%= f.label :ingangsdatum %><br />
    <%= f.date_select :ingangsdatum %>
  </div>
  <div class="field">
    <%= f.label :einddatum %><br />
    <%= f.date_select :einddatum %>
  </div>
  <div class="field">
    <%= f.label :mutatie %><br />
    <%= f.number_field :mutatie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zorgproductgroeps/edit.html.erb
<h1>Editing zorgproductgroep</h1>

<%= render 'form' %>

<%= link_to 'Show', @zorgproductgroep %> |
<%= link_to 'Back', zorgproductgroeps_path %>

app/views/zorgproductgroeps/index.html.erb
<h1>Listing zorgproductgroeps</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Omschrijving</th>
    <th>Ingangsdatum</th>
    <th>Einddatum</th>
    <th>Mutatie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zorgproductgroeps.each do |zorgproductgroep| %>
  <tr>
    <td><%= zorgproductgroep.code %></td>
    <td><%= zorgproductgroep.omschrijving %></td>
    <td><%= zorgproductgroep.ingangsdatum %></td>
    <td><%= zorgproductgroep.einddatum %></td>
    <td><%= zorgproductgroep.mutatie %></td>
    <td><%= link_to 'Show', zorgproductgroep %></td>
    <td><%= link_to 'Edit', edit_zorgproductgroep_path(zorgproductgroep) %></td>
    <td><%= link_to 'Destroy', zorgproductgroep, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zorgproductgroep', new_zorgproductgroep_path %>

app/views/zorgproductgroeps/new.html.erb
<h1>New zorgproductgroep</h1>

<%= render 'form' %>

<%= link_to 'Back', zorgproductgroeps_path %>

app/views/zorgproductgroeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @zorgproductgroep.code %>
</p>

<p>
  <b>Omschrijving:</b>
  <%= @zorgproductgroep.omschrijving %>
</p>

<p>
  <b>Ingangsdatum:</b>
  <%= @zorgproductgroep.ingangsdatum %>
</p>

<p>
  <b>Einddatum:</b>
  <%= @zorgproductgroep.einddatum %>
</p>

<p>
  <b>Mutatie:</b>
  <%= @zorgproductgroep.mutatie %>
</p>


<%= link_to 'Edit', edit_zorgproductgroep_path(@zorgproductgroep) %> |
<%= link_to 'Back', zorgproductgroeps_path %>

app/views/zorgproducts/_form.html.erb
<%= form_for(@zorgproduct) do |f| %>
  <% if @zorgproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zorgproduct.errors.count, "error") %> prohibited this zorgproduct from being saved:</h2>

      <ul>
      <% @zorgproduct.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :omschrijving %><br />
    <%= f.text_area :omschrijving %>
  </div>
  <div class="field">
    <%= f.label :ingangsdatum %><br />
    <%= f.date_select :ingangsdatum %>
  </div>
  <div class="field">
    <%= f.label :einddatum %><br />
    <%= f.date_select :einddatum %>
  </div>
  <div class="field">
    <%= f.label :mutatie %><br />
    <%= f.number_field :mutatie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zorgproducts/edit.html.erb
<h1>Editing zorgproduct</h1>

<%= render 'form' %>

<%= link_to 'Show', @zorgproduct %> |
<%= link_to 'Back', zorgproducts_path %>

app/views/zorgproducts/index.html.erb
<h1>Listing zorgproducts</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Omschrijving</th>
    <th>Ingangsdatum</th>
    <th>Einddatum</th>
    <th>Mutatie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zorgproducts.each do |zorgproduct| %>
  <tr>
    <td><%= zorgproduct.code %></td>
    <td><%= zorgproduct.omschrijving %></td>
    <td><%= zorgproduct.ingangsdatum %></td>
    <td><%= zorgproduct.einddatum %></td>
    <td><%= zorgproduct.mutatie %></td>
    <td><%= link_to 'Show', zorgproduct %></td>
    <td><%= link_to 'Edit', edit_zorgproduct_path(zorgproduct) %></td>
    <td><%= link_to 'Destroy', zorgproduct, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zorgproduct', new_zorgproduct_path %>

app/views/zorgproducts/new.html.erb
<h1>New zorgproduct</h1>

<%= render 'form' %>

<%= link_to 'Back', zorgproducts_path %>

app/views/zorgproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @zorgproduct.code %>
</p>

<p>
  <b>Omschrijving:</b>
  <%= @zorgproduct.omschrijving %>
</p>

<p>
  <b>Ingangsdatum:</b>
  <%= @zorgproduct.ingangsdatum %>
</p>

<p>
  <b>Einddatum:</b>
  <%= @zorgproduct.einddatum %>
</p>

<p>
  <b>Mutatie:</b>
  <%= @zorgproduct.mutatie %>
</p>


<%= link_to 'Edit', edit_zorgproduct_path(@zorgproduct) %> |
<%= link_to 'Back', zorgproducts_path %>